// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdwizlvmaavmgjagmuyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkd2l6bHZtYWF2bWdqYWdtdXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjY3MDEsImV4cCI6MjA1OTc0MjcwMX0.C8l1OBNBzLqBvJvTuoHmhS4Qbb9_qYhZt5fYINNZbIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);